### ISSUE TITLE
no decoys with csv input

### ISSUE THREAD

**Issue by swlenz** [Rappsilber-Laboratory/xiView#356]
Maybe I'm doing something wrong, but when I use a csv input I can't see any decoys (wanted to specifically look at them).

**Comment by colin-combe** [comment]
> Maybe I'm doing something wrong
more likely its the website

Can you see the decoys in the small score histogram in the filter bar at the bottom?

If you are looking at what was previously called the 'validation' page then decoys should be there. To get to the validation page you need to enable the 'spectra only' column on the history page (or just edit the url changing 'network' to 'validate').

I think the 'decoys' checkbox is missing from the xiview validation page, it was alongside the manual validation status controls (A, B, C, etc) and these got changed. The xiView 'validation page' (which doesn't allow validation) is always showing both decoys and targets - I can change this to meet your needs.
 
If you are looking at the network page then decoys aren't really displayed there. 
(Except that they are. They appear in the scatterplots, so its possible to select them there.)

Surprisingly long message... also, email me the CSV file if confusion continues

**Comment by colin-combe** [comment]
speaking to @swlenz,  this is a +1 for a decoys checkbox in the filter bar

**Comment by colin-combe** [comment]
@swlenz is happy just to close this, no one really remembers what this was originally about
