### ISSUE TITLE
Custom Layout for Subnetworks - Linewidth & #links

### ISSUE THREAD

**Issue by ludsinn** [Rappsilber-Laboratory/xiView#436]
Hey,

it would be nice if one could manually set the width of the lines illustrating how many links were detected between proteins in a given network.
The issue arises if one wants to compare several subnetworks that differ in their number of connecting links: For the network with a huge number of links the max. width is the same as for a network with only a few.

Thanks
Ludwig

**Comment by colin-combe** [comment]
Hi Ludwig,

yep, there was another request like this recently. They asked to be able to lock the mapping between number of unique residue pairs for a PPI and the width of the grey line.  

It used to work differently, so the line widths were predetermined and comparable between searches. We were asked to change this so it was relative to the maximum number of currently visible unique distance restraints between a PPI. 

Need new something that works for both cases,
cheers,
c

**Comment by colin-combe** [comment]
@ludsinn - should be that you can now manually set the width of the lines illustrating how many links were detected between proteins.

Works like this - by default its in 'auto' mode and behaves as it did before. If you enter a number in the "Link Width" input field (top right) it then fixes the grey background link widths to this many pixels per Unique Linked Residue Pair. So yo can make the widths comparable between datasets.

To put it back into auto mode delete the contents of the input field and press return.

It's been deployed on the lab version and the public version. Let me know if any problems.

c
