### ISSUE TITLE
Protein Spheres get lost Network representation

### ISSUE THREAD

**Issue by ludsinn** [Rappsilber-Laboratory/xiview#480]
Hello,

I think this is a bug. I had it in the past that the protein spheres disappeared upon zooming out/moving the network so that only the links remained (see screenshot).

I use Firefox Version 68.0.2 (32-bit)  and did several browser hard resets, yet the issue occurs again occasionally.

Thanks.
Ludwig
![Clipboard02](https://user-images.githubusercontent.com/18328751/65040452-b776b080-d954-11e9-8e6f-26cda7422fa3.jpg)

**Comment by ludsinn** [comment]
Update:
This seems to occur in conjunction with unticking "labels" and then resetting the layout by clicking on "Auto".

If I do it the other way around, it works as expected.

**Comment by colin-combe** [comment]
i'll leave this open, its still something I need to fix,
c

**Comment by colin-combe** [comment]
i can't currently replicate this (it's ok in firefox version I use),
does it still happen if you use Chrome?

**Comment by ludsinn** [comment]
When running it in Chrome (updated to Version 77.0.3865.75 (64-Bit), yesterday) on my PC I am facing no issues.

On the server, however, we use Firefox (Version 68.0.2 (32-bit)) which displays the weird behaviour stated above.
Of note, zooming in restores the protein spheres.

Instead, I found something else with Firefox (sorry):
This time, the proteins are correctly shown but the links are not. When dragging each protein (individually!) point a bit, the link lines reappear.
