### ISSUE TITLE
Cluster networks in xiView based on a selection

### ISSUE THREAD

**Issue by ludsinn** [Rappsilber-Laboratory/xiView#484]
Hi,

In the hope that this is not something that has been requested earlier...
I was wondering how to make creating a figure of a (sub)network more efficient in xiView.

For exporting plots, it would be nice to have an automated clustering of (a core) complex that is in focus of the investigator.

Example: Say, a complex with 4 members and all their interactors is displayed. The automatic layout is a big help in formatting these networks but does not know one is focussing on this complex which I'd like to have in the center with all interactors surrounding it (with the restriction that the link's lines & the ID labels show as little overlap as possible.

Cheers
L

**Comment by colin-combe** [comment]
@ludsinn - I think the grouping functionality covers this?

we can take up what the grouping does and doesn't do on the slack channel

I'll not close this one just yet, but apart from centring the selected complex you mainly have this I think

**Comment by ludsinn** [comment]
@colin-combe 
yes, the grouping covers this now. many thanks!
btw, the current layout centers the protein names on the nodes which will become very handy for dense networks (more to be seen in the future ;-) )
cheers

**Comment by colin-combe** [comment]
> the current layout centers the protein names on the nodes

yep, it makes it easier for the layout algorithm by making things both smaller and squarer
