### ISSUE TITLE
Table of matches downloaded from Browser needs to change

### ISSUE THREAD

**Issue by fjoreilly** [Rappsilber-Laboratory/xiview#502]
Autovailidated doesnt mean anything so should be removed from output.

Matches should be annotated if they are decoys or not.

**Comment by colin-combe** [comment]
> Autovailidated doesnt mean anything so should be removed from output.

Well, I guess it does too people using autovalidation. But perhaps this column in unnecessary, we should ask Juan? ( @juanzou ) 
You could remove it from your csv output quite easily using spreadsheet software.

> Matches should be annotated if they are decoys or not.

Do you see a column called "DecoyType" containing either "TT", "TD" or "DD"?

**Comment by fjoreilly** [comment]
Ah, Its good in Matches, but not in the links output

**Comment by colin-combe** [comment]
@fjoreilly - the decoy info should be there for link CSV in lab version. You'll probably want it for PPI export aswell?

This change will appear in public xiView version middle next week. (I'm at EBI this week and wouldn't have time to fix it before Martin's tutorials if merging changes into public version breaks things.)

I'll leave this open until its as you want it (prob including PPI export) in both public and lab versions

**Comment by colin-combe** [comment]
Actually, it should be in public xiView now. Martin asked me to merge for other reasons.
