### ISSUE TITLE
Clustering based on complex membership

### ISSUE THREAD

**Issue by fjoreilly** [Rappsilber-Laboratory/xiView#507]
I know that this idea from Colin automatically putting things in 'bags' is a way away right now. Instead would it be possible that in the 'Protein selection' tab that I could chose proteins based on their 'value' from the metadata. I could then hide all other proteins and 'auto' arrange these. (I'm currently using the public version.

**Comment by colin-combe** [comment]
isn't this the same as filtering based on protein meta data?
i.e. once you had filtered out the proteins whose metadata value didn't meet some criteria then you could click auto layout?

**Comment by fjoreilly** [comment]
It is actually

**Comment by fjoreilly** [comment]
Ok then here is one. Lets say I arrange my 3 complexes I want (so I have placed them at four corners of my screen). Can I then somehow click 'auto' and the rest of the proteins move around but those that I want to remain fixed will remain fixed in place?

**Comment by colin-combe** [comment]
@fjoreilly 
> Ok then here is one. Lets say I arrange my 3 complexes I want (so I have placed them at four corners of my screen). Can I then somehow click 'auto' and the rest of the proteins move around but those that I want to remain fixed will remain fixed in place?

Ok - yes, you can. There's a option in the 'display' menu for fixing the selected proteins in the autolayout. I *think* its working

**Comment by colin-combe** [comment]
@fjoreilly - so... you can put things in bags, the bags can also be collapsed, the auto layout should respect bag membership and try to stop them overlapping

fixing selected nodes in the auto layout was also done
 
issues related to filtering on metadata go back to the start (e.g. https://github.com/Rappsilber-Laboratory/xi3-issue-tracker/issues/33) but weren't done, its a separate issue... 

closing, reopen if you see a reason to do so
