### ISSUE TITLE
website unavailable

### ISSUE THREAD

**Issue by jayieh** [Rappsilber-Laboratory/xiView#548]
Hi xiView team,

the website is currently not available - I checked from both the university LAN as well as by LTE connection...

could you look into this?

Best

Jürgen

**Comment by jayieh** [comment]
it works again

**Comment by jayieh** [comment]
Hi xiView team,

the website is currently not available again - I checked from both the university LAN as well as my LTE connection... When I ping xiview.org, the ip is resolved, but does not respond...

could you look into this?

Best

Jürgen

**Comment by colin-combe** [comment]
yes, we have ongoing network issues at the moment, sorry

**Comment by jayieh** [comment]
any estimate on when to expect the site to be fully functional again?

**Comment by colin-combe** [comment]
i think it could be next week - fixing it is perhaps affected by "strike action at University of Edinburgh for a period of 14 days between Monday 24th February and Friday 13th March."

**Comment by jayieh** [comment]
thanks for the update!

**Comment by colin-combe** [comment]
it appears to be working again, but it's network connection doesn't seem that reliable at the moment,

let us know if it disappears again,
cheers,
colin

**Comment by colin-combe** [comment]
things should be a bit better now, please let us know if it goes down again
