### ISSUE TITLE
filtering by uniprot id not working

### ISSUE THREAD

**Issue by swlenz** [Rappsilber-Laboratory/xiView#549]
Hi, 
for me filtering by uniprot id worked before, now I can't do it anymore (neither in description or name). 
Could you bring it back please?
Thanks!

**Comment by colin-combe** [comment]
Hi Swantje,
yep, I can. 

Are you using the public version or the lab version?
If its the lab version then this isn't super relevant right now as the lab version is out of action...

**Comment by colin-combe** [comment]
OK - the 'Name' filter, now labelled 'Name / Acc.' also applies to the accession number,

reopen if not working,
cheers,
c
