### ISSUE TITLE
Allow fasta with the silly end of line that TextEdit on Mac adds

### ISSUE THREAD

**Issue by fjoreilly** [Rappsilber-Laboratory/xiView#550]
Text Edit is the only 'simple' text editor on Macs and it seems to add nonsense to the end of every line that aren't obvious in this editor (you can see them in Notepad+   on Windows).

**Comment by colin-combe** [comment]
ok, roger that, I'll see what I can do. Could you provide an example of the files please?

(p.s. I still think brexit ain't gonna happen)

**Comment by colin-combe** [comment]
@fjoreilly - do your messed up fasta files work now?
