### ISSUE TITLE
Filter sequence by modfications as numbers not working

### ISSUE THREAD

**Issue by lars-kolbowski** [Rappsilber-Laboratory/xiview#555]
It's not possible to filter "sequence" by modifications that are numbers and brackets, e.g. (82.04). Probably these chars are not allowed, even though they are valid modification names.
![image](https://github.com/Rappsilber-Laboratory/xiView/assets/15844484/0be16beb-0ee7-4681-a0cd-5f055d3edaec)

**Comment by colin-combe** [comment]
yep, looks that way
