### ISSUE TITLE
Not all clickable crosslinks open relevant spectra

### ISSUE THREAD

**Issue by ciancone94** [Rappsilber-Laboratory/xiView#556]
Hello,

Previously, I have been using XiView (the public website version, xiview.org) to upload XiFDR CSM outputs with corresponding .mgfs and FASTAs with great success; however, recently, when trying to load up spectra corresponding to crosslinks in a photo-leucine crosslinking dataset, many of the spectra will not load. I have not run into this issue with DSSO or SDA crosslinking datasets. I have checked that the relevant .mgfs have been uploaded. Sometimes spectra will load as I click through the PSM IDs and sometimes they won't, with no apparent rhyme or reason as to why. I've ruled out that certain mgfs are the reason as well. Additionally, this seems to be an issue for higher-scored crosslinks; depending on the crosslink, PSMs with lower scores sometimes load a spectrum that won't load for a higher score.

As a caveat, this data is only looking at a purified complex. As there wasn't a lot of linears, I had to boost residue_pairs on XiFDR instead of protein_pairs. Not sure if this matters, but the FDR is quite high.

Thank you,

Anthony

**Comment by colin-combe** [comment]
for the PSMs that don't display their spectrum, 
if you open the debugger in the browser (CTRL -SHIFT - J) and look at the console, do you see an error message that starts like:
`annotation request failed: SyntaxError: Unexpected token`

**Comment by colin-combe** [comment]
Hmmm. Maybe the error looks different depending on which browser you're using.

Is it working now or still broken?

Colin

**Comment by ciancone94** [comment]
Seems like it's working now, thanks for the fix!
