### ISSUE TITLE
XiFDR output files do not have correct headers for XiView - incorrect ppm error as a result

### ISSUE THREAD

**Issue by ciancone94** [Rappsilber-Laboratory/xiview#557]
Hello, so we are currently trying to fix our XiFDR outputs so that XiView can actually correctly calculate ppm error, as currently, it returns negative or nonsensical values with our setup. 

Francis directed me here: https://xiview.org/xiNET_website/csv-formats.php, which gives me the titles for the columns for the csvs. The current XiFDR output gives a column called 'PrecurserMZ' and 'CalcMZ', neither of which match what is listed on the website for csvs to be interpreted by XiView ('ExpMz' and 'CalcMz'). When I try changing them, the csv is now interpreted as the 'Minimal csv' and throws the following error:

"log id: 63pqp3kasjsamiu418bv7r3i7l_1689356807.log (include this in the github issue)
error type: Error
message: Required csv column abspos1 missing
id: undefined"

even though it is not a minimal csv, as without changing the file, there is no abspos1 column anyways.

I can define PrecerserMz as ExpMz but to properly get ppm error you need the masses, not the m/zs. So changing this gives ppm errors in the thousands.

Any idea how to fix XiFDR outputs to work properly in XiView? Thanks. For context, we use the XiFDR GUI to write outputs into a specified directory and we upload the CSM csv to XiView.

Anthony

**Comment by colin-combe** [comment]
Hi Anthony,

yes, that's right, the input and output for our tools don't match up:
https://github.com/Rappsilber-Laboratory/xiFDR/issues/33

> Any idea how to fix XiFDR outputs to work properly in XiView?

use the mzIdentML output from xiFDR instead?  (@fjoreilly)

cheers,
Col

**Comment by ciancone94** [comment]
Thanks Colin, I was just wondering if changing the csv column titles would be a simpler way. I'm going to try to keep messing around with it for a bit to see if I can trick it. 

>use the mzIdentML output from xiFDR instead?

One issue we have with the mzIdentML output from the XiFDR GUI is that the 'write' button doesn't actually work for us (no output is generated), even when filling out all relevant parameters. Should we be using XiFDR through the command line to generate the mzIdentML instead? Or are we missing something simple? Francis watched me try it and he was surprised it didn't work as he remembered.

Thanks,

Anthony

**Comment by colin-combe** [comment]
> I was just wondering if changing the csv column titles would be a simpler way. I'm going to try to keep messing around with it for a bit to see if I can trick it.

renaming "exp m/z" to "ExpMz" will get you part of the way there but I think you'll need to do a calculation to recover the "CalcMZ" column.

> One issue we have with the mzIdentML output from the XiFDR GUI is that the 'write' button doesn't actually work for us (no output is generated)

OK, i don't know anything about that - you should make a GH issue on the xiFDR project,
cheers,
C
