### ISSUE TITLE
Any way to visualize linears and decoys on the public XiView?

### ISSUE THREAD

**Issue by ciancone94** [Rappsilber-Laboratory/xiView#558]
I was wondering if there was any way to visualize linear and decoy matches from a dataset on the public version of XiView. Francis informed me that the non-public version has these options. If not, are there alternatives you can think of? Such as spoofing the data that gets uploaded to XiView? I.e., listing the linears and decoys as matches in the CSM that gets uploaded.

Thanks,

Anthony

**Comment by colin-combe** [comment]
Hi Amtony,
Sorry for delay getting back to you, I was on holiday.

> Francis informed me that the non-public version has these options.

Yes, the same should be available on the public version but its currently inaccessible and broken...

I'll get back to you in a day or so,
cheers,
Colin

**Comment by colin-combe** [comment]
Hi Antony,

as a quick test, if you replace the word "network" with the word "validate" in the URL you are accessing, does that page allow you to do what you want.

E.g. https://xiview.org/xi3/validate.php?upload=547-90828-08990-28852-02225

i know its not ideal having to manually change the URL,

Col

**Comment by colin-combe** [comment]
did this work for you? (@ciancone94 @fjoreilly )

**Comment by colin-combe** [comment]
> Any idea how to remove consecutive peptides though? 

that's currently not something you can do in the xiVIEW interface 
 
>Or is this just going to be something I need to discuss with colleagues about how to script these out before loading data to XiFDR?

there might already be options in xiSEARCH or xiFDR related to this - @lutzfischer?

**Comment by lutzfischer** [comment]
xiFDR has an option to ignore consecutive peptides:
![image](https://github.com/Rappsilber-Laboratory/xiView/assets/6330440/d0925cb7-8c5a-4760-9d2e-cad4a06e3a27)

**Comment by ciancone94** [comment]
Ah, that's where it is. Okay, great, thank you.
