### ISSUE TITLE
Visualization Issues

### ISSUE THREAD

**Issue by ciancone94** [Rappsilber-Laboratory/xiview#559]
Whenever I load up XiView links, the interlinks now no longer show when I aggregate multiple datasets. Here is one error I got:

<img width="623" alt="image" src="https://github.com/Rappsilber-Laboratory/xiview/assets/131007826/38819de4-7094-4e1f-bfa5-692c57292485">

Doesn't seem to matter if I make all datasets as "1" or "1", "2", "3", etc. for aggregation.

Thanks,

Anthony

**Comment by colin-combe** [comment]
fixed?

**Comment by ciancone94** [comment]
Looks like it's all working now - thanks!
