### ISSUE TITLE
MS2 spectrum in the "validate" part cannot be displayed.

### ISSUE THREAD

**Issue by 3222010198** [Rappsilber-Laboratory/xiview#560]
Dear Colin，
After I uploaded the data, I changed "network" to "spectrum" in the URL, but the MS2 spectrum doesn't show up!
Can you please check if something is wrong. Thank you very much.

![image](https://github.com/Rappsilber-Laboratory/xiview/assets/150008585/63fb0263-5111-49c1-a9d2-3c07bc8c9ed7)

**Comment by colin-combe** [comment]
Hi,

Thanks for the error report. Yes, I made a mistake - should be fixed now.

Best wishes,
Colin
