### ISSUE TITLE
Can not load XiSearch UV-crosslinking result to XiView 

### ISSUE THREAD

**Issue by WeiqiangChen** [Rappsilber-Laboratory/xiview#563]
I can not load XiSearch result of UV-crosslinking, diazK. It showed the following error.

log id: 9irk5qs9lc9djt93jbkpknb7pp_1714456729.log (include this in the github issue)
error type: Error
message: name
id: undefined

I also tried to remove the (photo) in the fasta and got the same error.

**Comment by colin-combe** [comment]
i suspect this: https://github.com/Rappsilber-Laboratory/xiFDR/issues/39

also, https://github.com/Rappsilber-Laboratory/xiview/issues/561
> Could you search the mzId file for `<cvParam></cvParam>`?
If you find it then that is the problem and replacing them with empty strings may make it work.

if that fixes it maybe comment on https://github.com/Rappsilber-Laboratory/xiFDR/issues/39 asking for fix
